# =============================================================================
# Antora Build & Publish GitHub Action
# =============================================================================
#
# This action builds Antora documentation sites with full support for:
#   - Private repository authentication (GitHub, GitLab, Bitbucket)
#   - Multi-repository content aggregation
#   - Custom Antora extensions
#   - Configurable playbook paths
#
# -----------------------------------------------------------------------------
# ABOUT GIT CREDENTIALS IN ANTORA
# -----------------------------------------------------------------------------
#
# Antora fetches content from Git repositories at build time. When those repos
# are private, Antora needs credentials to access them. There are several ways
# to provide these credentials:
#
# 1. GIT_CREDENTIALS environment variable (recommended for CI)
#    Format: https://<token>@<host> or https://<user>:<token>@<host>
#    Example: https://x-access-token:ghp_xxx@github.com
#
# 2. git.credentials key in playbook (NOT recommended - exposes tokens)
#    Use git.credentials.path or git.credentials.contents instead.
#
# 3. .git-credentials file (used internally by this action)
#    Standard Git credential storage format.
#
# The GIT_CREDENTIALS format supports multiple hosts (one per line):
#    https://x-access-token:ghp_xxx@github.com
#    https://oauth2:glpat_xxx@gitlab.com
#    https://x-token-auth:xxx@bitbucket.org
#
# -----------------------------------------------------------------------------
# PERSONAL ACCESS TOKEN (PAT) SCOPES
# -----------------------------------------------------------------------------
#
# GitHub:
#   - For public repos: No token needed
#   - For private repos: Token needs 'repo' scope (full repo access)
#   - Fine-grained tokens: Need "Contents" read access on target repos
#
# GitLab:
#   - For private repos: Token needs 'read_repository' scope
#   - Project access tokens work too (more restrictive, recommended)
#
# Bitbucket:
#   - For private repos: App password with 'repository:read' permission
#
# -----------------------------------------------------------------------------
# WHY LOCAL INSTALLATION (NOT GLOBAL)
# -----------------------------------------------------------------------------
#
# This action REQUIRES a package.json with Antora as a local dependency.
# We do NOT support global installation (`npm install -g`) because:
#
#   1. Reproducibility: Local install + lockfile = same version every build
#   2. Version control: package.json pins the exact Antora version
#   3. Best practice: The Antora docs recommend local installation
#   4. Avoids "works on my machine": CI and local dev use same versions
#
# Global installs cause problems because:
#   - "latest" resolves to whatever version exists at build time
#   - No lockfile means no guarantee of consistent builds
#   - Breaking changes in new versions can silently break your CI
#
# See: https://docs.antora.org/antora/latest/install/install-antora/#locally-vs-globally
#
# Your package.json should include:
#   {
#     "devDependencies": {
#       "@antora/cli": "^3.1",
#       "@antora/site-generator": "^3.1"
#     }
#   }
#
# -----------------------------------------------------------------------------
# SEE ALSO
# -----------------------------------------------------------------------------
#
# For a DIY workflow without this action (more transparent, same result), see:
#   https://github.com/amdphreak/antora-workflow-templates
#
# The templates repo contains side-by-side examples showing:
#   - diy-workflow.yml: All steps spelled out explicitly
#   - action-workflow.yml: Using this reusable action
#
# =============================================================================

name: 'Antora Build'
description: >
  Build Antora documentation sites with support for private repositories,
  multi-repo aggregation, and custom extensions. Outputs a static site
  ready for deployment to GitHub Pages, Netlify, or any static host.
  Requires package.json with @antora/cli as a dependency.
author: 'AMDphreak'

branding:
  icon: 'book-open'
  color: 'blue'

inputs:
  playbook:
    description: |
      Path to the Antora playbook file (YAML).
      Common names: antora-playbook.yml, site.yml, antora.yml
    required: false
    default: 'antora-playbook.yml'

  # ---------------------------------------------------------------------------
  # CREDENTIAL INPUTS
  # ---------------------------------------------------------------------------
  # These inputs configure authentication for private content repositories.
  # You typically only need ONE of these methods, not all of them.
  # ---------------------------------------------------------------------------

  git_credentials:
    description: |
      Git credentials in .git-credentials format for accessing private repos.
      Format: https://<user>:<token>@<host>
      
      For GitHub PAT:  https://x-access-token:${{ secrets.GH_PAT }}@github.com
      For GitLab PAT:  https://oauth2:${{ secrets.GL_PAT }}@gitlab.com
      For Bitbucket:   https://x-token-auth:${{ secrets.BB_TOKEN }}@bitbucket.org
      
      Multiple credentials (one per line) for multi-host setups:
        https://x-access-token:${{ secrets.GH_PAT }}@github.com
        https://oauth2:${{ secrets.GL_PAT }}@gitlab.com
      
      This is the RECOMMENDED way to provide credentials in GitHub Actions.
    required: false

  github_token:
    description: |
      GitHub token for accessing private GitHub repositories only.
      This is a convenience input - equivalent to setting git_credentials with:
        https://x-access-token:<token>@github.com
      
      You can use the automatic GITHUB_TOKEN for repos in the same org,
      or a PAT with 'repo' scope for cross-org private repos.
      
      Note: GITHUB_TOKEN only has access to the current repository by default.
      For multi-repo setups with private repos, use a PAT instead.
    required: false

  # ---------------------------------------------------------------------------
  # BUILD CONFIGURATION
  # ---------------------------------------------------------------------------

  node_version:
    description: |
      Node.js version to use. Antora 3.x requires Node.js 16+.
    required: false
    default: '20'

  # ---------------------------------------------------------------------------
  # OUTPUT CONFIGURATION
  # ---------------------------------------------------------------------------

  output_dir:
    description: |
      Directory where the generated site will be written.
      This should match the 'dir' setting in your playbook's output configuration,
      or leave it to the playbook default (usually 'build/site').
    required: false
    default: 'build/site'

  fetch:
    description: |
      Whether to fetch updates from content source repositories.
      Set to 'true' to always fetch latest content.
      Set to 'false' to use cached content (faster for repeated builds).
    required: false
    default: 'true'

  log_level:
    description: |
      Antora log level: 'fatal', 'error', 'warn', 'info', 'debug', 'all'
    required: false
    default: 'warn'

  working_directory:
    description: |
      Directory to run the build in. Useful for monorepos where the
      Antora playbook is in a subdirectory (e.g., 'docs' or 'site').
    required: false
    default: '.'

outputs:
  site_dir:
    description: 'Path to the generated site directory'

runs:
  using: 'composite'
  steps:
    # -------------------------------------------------------------------------
    # Step 1: Verify package.json exists
    # -------------------------------------------------------------------------
    # We require local installation for reproducible builds.
    # See header comments for why global installs are not supported.
    # -------------------------------------------------------------------------
    - name: Verify package.json exists
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        if [ ! -f "package.json" ]; then
          echo "::error::No package.json found in ${{ inputs.working_directory }}"
          echo ""
          echo "This action requires Antora to be installed as a local dependency."
          echo "Global installation (npm install -g) is not supported because it"
          echo "leads to unreproducible builds."
          echo ""
          echo "Please create a package.json with Antora dependencies:"
          echo ""
          echo '  {'
          echo '    "devDependencies": {'
          echo '      "@antora/cli": "^3.1",'
          echo '      "@antora/site-generator": "^3.1"'
          echo '    }'
          echo '  }'
          echo ""
          echo "Then run: npm install"
          echo ""
          echo "See: https://docs.antora.org/antora/latest/install/install-antora/#locally-vs-globally"
          exit 1
        fi
        
        # Check if @antora/cli is in dependencies
        if ! grep -q "@antora/cli" package.json; then
          echo "::warning::@antora/cli not found in package.json - make sure Antora is installed"
        fi

    # -------------------------------------------------------------------------
    # Step 2: Setup Node.js
    # -------------------------------------------------------------------------
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    # -------------------------------------------------------------------------
    # Step 3: Detect package manager (pnpm vs npm)
    # -------------------------------------------------------------------------
    - name: Detect package manager
      id: detect-pm
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        if [ -f "pnpm-lock.yaml" ]; then
          echo "manager=pnpm" >> $GITHUB_OUTPUT
          echo "Detected pnpm (pnpm-lock.yaml found)"
        else
          echo "manager=npm" >> $GITHUB_OUTPUT
          echo "Using npm"
        fi

    # -------------------------------------------------------------------------
    # Step 4: Setup pnpm (if detected)
    # -------------------------------------------------------------------------
    - name: Setup pnpm
      if: steps.detect-pm.outputs.manager == 'pnpm'
      uses: pnpm/action-setup@v4
      with:
        package_json_file: ${{ inputs.working_directory }}/package.json

    # -------------------------------------------------------------------------
    # Step 5: Configure Git Credentials
    # -------------------------------------------------------------------------
    # This step sets up authentication for private repositories.
    # Antora reads credentials from the GIT_CREDENTIALS environment variable
    # or from a .git-credentials file.
    # -------------------------------------------------------------------------
    - name: Configure Git credentials
      shell: bash
      env:
        GIT_CREDENTIALS_INPUT: ${{ inputs.git_credentials }}
        GITHUB_TOKEN_INPUT: ${{ inputs.github_token }}
      run: |
        # Create credentials file location
        CREDS_FILE="$HOME/.git-credentials"
        
        # Priority: git_credentials > github_token
        if [ -n "$GIT_CREDENTIALS_INPUT" ]; then
          echo "::debug::Using git_credentials input"
          echo "$GIT_CREDENTIALS_INPUT" > "$CREDS_FILE"
        elif [ -n "$GITHUB_TOKEN_INPUT" ]; then
          echo "::debug::Using github_token input"
          echo "https://x-access-token:${GITHUB_TOKEN_INPUT}@github.com" > "$CREDS_FILE"
        fi
        
        # Configure git to use the credentials file if it exists
        if [ -f "$CREDS_FILE" ]; then
          chmod 600 "$CREDS_FILE"
          git config --global credential.helper "store --file=$CREDS_FILE"
          echo "::debug::Git credentials configured"
        fi

    # -------------------------------------------------------------------------
    # Step 6: Install Dependencies
    # -------------------------------------------------------------------------
    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        PKG_MANAGER: ${{ steps.detect-pm.outputs.manager }}
      run: |
        if [ "$PKG_MANAGER" = "pnpm" ]; then
          echo "Installing dependencies with pnpm..."
          pnpm install --frozen-lockfile
        else
          echo "Installing dependencies with npm..."
          npm ci
        fi

    # -------------------------------------------------------------------------
    # Step 7: Build the Antora Site
    # -------------------------------------------------------------------------
    - name: Build Antora site
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        PLAYBOOK: ${{ inputs.playbook }}
        FETCH: ${{ inputs.fetch }}
        LOG_LEVEL: ${{ inputs.log_level }}
        PKG_MANAGER: ${{ steps.detect-pm.outputs.manager }}
        # Pass credentials via environment for Antora's git operations
        GIT_CREDENTIALS: ${{ inputs.git_credentials }}
      run: |
        # Build command arguments
        ARGS=""
        
        if [ "$FETCH" = "true" ]; then
          ARGS="$ARGS --fetch"
        fi
        
        ARGS="$ARGS --log-level $LOG_LEVEL"
        
        # Run antora using the appropriate package manager
        if [ "$PKG_MANAGER" = "pnpm" ]; then
          echo "Running: pnpm exec antora $ARGS $PLAYBOOK"
          pnpm exec antora $ARGS "$PLAYBOOK"
        else
          echo "Running: npx antora $ARGS $PLAYBOOK"
          npx antora $ARGS "$PLAYBOOK"
        fi

    # -------------------------------------------------------------------------
    # Step 8: Set Outputs
    # -------------------------------------------------------------------------
    - name: Set outputs
      shell: bash
      env:
        OUTPUT_DIR: ${{ inputs.output_dir }}
        WORKING_DIR: ${{ inputs.working_directory }}
      run: |
        if [ "$WORKING_DIR" = "." ]; then
          echo "site_dir=$OUTPUT_DIR" >> $GITHUB_OUTPUT
        else
          echo "site_dir=$WORKING_DIR/$OUTPUT_DIR" >> $GITHUB_OUTPUT
        fi
